mongodb retry for travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,6 +5,16 @@ node_js:
   - "0.10"
 
 before_script:
+  # Test MongoDB connection; Fails after tries
+  - |
+    echo "Testing MongoDB connection...";tries=4;
+    i=0;
+    while [ $i -lt $tries ]; do fail=$(mongo --eval db 2>&1 >/dev/null | grep "connect failed");
+      if [ "$fail" ] && [ $[ $i+1 ] -eq $tries ] ; then echo "Error: Could not connect to mongodb"; exit 1;
+      elif [ "$fail" ]; then sleep 3; i=$[ $i+1 ];
+      else echo "OK"; i=$tries; fi;
+    done
+  - echo "... MongoDB OK"
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - npm start > /dev/null &
